# Generated by Django 3.1.3 on 2023-05-10 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_auto_20201118_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='slug',
        ),
    ]
