# Generated by Django 3.1.3 on 2023-05-13 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_remove_classroom_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassroomTeachers',
        ),
    ]
