# Generated by Django 3.1.3 on 2023-05-18 09:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classroom', '0007_auto_20230518_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='users',
        ),
        migrations.AddField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(related_name='student_classrooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classroom',
            name='teachers',
            field=models.ManyToManyField(related_name='teacher_classrooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
