# Generated by Django 3.1.3 on 2023-05-23 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0010_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
