# Generated by Django 3.1.3 on 2023-06-10 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classroom', '0016_remove_classroom_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.classroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'classroom_classroom_users',
            },
        ),
        migrations.AddField(
            model_name='classroom',
            name='users',
            field=models.ManyToManyField(related_name='classrooms', through='classroom.ClassroomUsers', to=settings.AUTH_USER_MODEL),
        ),
    ]
