# Generated by Django 3.1.3 on 2023-05-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20201127_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='marks',
            field=models.IntegerField(),
        ),
    ]
