# Generated by Django 3.1.3 on 2023-06-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20230503_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='marks',
            field=models.IntegerField(default=12),
        ),
    ]
