# Generated by Django 3.1.3 on 2023-06-07 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_form'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Form',
        ),
    ]
