# Generated by Django 3.1.3 on 2023-06-11 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0019_auto_20230608_1335'),
        ('users', '0007_auto_20230608_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsform',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.form'),
        ),
    ]
