# Generated by Django 3.1.3 on 2023-05-03 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_privatecomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrivateComment',
        ),
    ]
