# Generated by Django 3.1.3 on 2023-06-11 16:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_auto_20230611_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
