# Generated by Django 3.1.3 on 2023-06-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_auto_20230611_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='mark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='topik',
            field=models.TextField(blank=True, null=True),
        ),
    ]
