# Generated by Django 3.1.3 on 2023-06-11 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0018_auto_20230610_2012'),
        ('journal', '0008_auto_20230611_2014'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='journal',
            unique_together={('classroom_user', 'created_at')},
        ),
    ]
