# Generated by Django 3.1.3 on 2023-06-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0009_auto_20230611_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='rating',
            field=models.IntegerField(choices=[(0, 'Dont Visited'), (1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six'), (7, 'Seven'), (8, 'Eight'), (9, 'Nine'), (10, 'Ten'), (11, 'Eleven'), (12, 'Twelve')]),
        ),
    ]
