# Generated by Django 3.1.3 on 2023-06-15 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0010_auto_20230611_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='mark',
        ),
    ]
