# Generated by Django 3.1.3 on 2023-05-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20230506_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_number', models.IntegerField(default=0)),
                ('starting_lesson', models.CharField(max_length=5)),
                ('ending_lesson', models.CharField(max_length=5)),
                ('pause', models.CharField(max_length=20)),
            ],
        ),
    ]
