# Generated by Django 3.1.3 on 2023-05-07 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20230507_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='pause',
            field=models.IntegerField(default=0),
        ),
    ]
