# Generated by Django 3.1.3 on 2023-05-07 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_auto_20230507_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='number_lesson',
        ),
    ]
