# Generated by Django 3.1.3 on 2023-05-07 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_remove_lesson_number_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='days',
        ),
        migrations.RemoveField(
            model_name='weekday',
            name='lessons',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.DeleteModel(
            name='Weekday',
        ),
    ]
