# Generated by Django 3.1.3 on 2023-05-07 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0015_auto_20230508_0052'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='Clas',
        ),
    ]
