# Generated by Django 3.1.3 on 2023-06-07 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0017_auto_20230510_2006'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clas',
            new_name='Group',
        ),
    ]
