# Generated by Django 3.1.3 on 2023-06-08 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_form'),
        ('schedule', '0018_auto_20230607_1959'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='Form',
        ),
    ]
